common: &common
  callback_url: http://test.local/verify
  return_url: http://test.local/verify
  cancel_url: http://test.local/cancel
  snd_id: sender

krediidipank:
  <<: *common
  certificate_path: ../certificates/pangalink_krediidipank_bank_cert.pem
  private_key_path: ../certificates/pangalink_krediidipank_user_key.pem
  private_key_secret: foobar
  snd_id: sender

lhv:
  <<: *common
  certificate_path: ../certificates/pangalink_lhv_bank_cert.pem
  private_key_path: ../certificates/pangalink_lhv_user_key.pem
  private_key_secret: foobar
  snd_id: sender

swedbank:
  <<: *common
  certificate_path: ../certificates/pangalink_swedbank_bank_cert.pem
  private_key_path: ../certificates/pangalink_swedbank_user_key.pem
  private_key_secret: foobar
  snd_id: sender

seb:
  <<: *common
  certificate_path: ../certificates/pangalink_seb_bank_cert.pem
  private_key_path: ../certificates/pangalink_seb_user_key.pem
  private_key_secret: foobar
  snd_id: sender

nordea:
  <<: *common
  # certificate_path: ../certificates/pangalink_nordea_bank_cert.pem
  # private_key_path: ../certificates/pangalink_nordea_user_key.pem
  private_key_secret: foobar
  snd_id: sender

danske:
  <<: *common
  certificate_path: ../certificates/pangalink_danske_bank_cert.pem
  private_key_path: ../certificates/pangalink_danske_user_key.pem
  private_key_secret: foobar
  snd_id: sender
